### ISSUE TITLE
New? Request Access

### ISSUE THREAD

**Issue by diamondstick** [StormlightTech/openCAD-php#113] opened 2017-09-24 06:36 UTC
### Expected behavior
Let me sign up
### Actual behavior
Just breaks the login form
### Steps to reproduce behavior
Press the New? Request Access button and try to signup.

**Comment by murfasa** [comment] 2017-09-24 17:59
What do you mean it just breaks the form? Any errors? Any error logs? Does it say anything?

**Comment by diamondstick** [comment] 2017-09-24 18:00
No errors i just cant click anything

**Comment by murfasa** [comment] 2017-09-24 18:01
Can I see a screenshot?

**Comment by murfasa** [comment] 2017-09-24 18:01
Do you have the newest version?

**Comment by diamondstick** [comment] 2017-09-24 18:02
Yes
https://gyazo.com/8ef2fa1ee9bd85d73c0eb8d8bce1cd4d

**Comment by murfasa** [comment] 2017-09-24 18:06
Can I have the link to your site?

**Comment by termanator1128** [comment] 2017-09-24 18:12
@murfasa I can confirm this error. Most likely the JS stuff that broke it.

**Comment by diamondstick** [comment] 2017-09-24 18:21
I sent it to you on discord

**Comment by termanator1128** [comment] 2017-09-24 19:05
This is due to a JS problem. Occurred after #101

**Comment by termanator1128** [comment] 2017-09-24 23:12
Issue is fixed with #117

**Closed by termanator1128** 2017-09-24 23:12 UTC
Labels: bug
