### ISSUE TITLE
Error when registering a new user First Responder

### ISSUE THREAD

**Issue by AAndersenLves** [StormlightTech/OpenCAD-php#425] opened 2022-07-02 00:26 UTC
********************************************************************************************************************************Describe the error**
A clear and concise description of what constitutes an error.

**For playback**
1. Go to the "home page".
2. Click on the "First Responder" button.
3. Fill out the form and click on the Request button
4. See the error section

**Expected behavior**
Message about successful registration

**Screenshots**
![image](https://user-images.githubusercontent.com/108557518/176979740-78898e44-751b-4c85-a1fb-a8f7a2a33b08.png)
Data Base MySQL:
![image](https://user-images.githubusercontent.com/108557518/176979758-d2bc588b-a9fc-4a2e-9868-203bf37342f9.png)
Admin Panel:
![image](https://user-images.githubusercontent.com/108557518/176979779-0cb7e1a0-6d76-4cd6-9fd9-a8d13cbc7026.png)

**Desktop (please fill in the following information):**
- OPERATING system: [for example, iOS] Windows 10
- Browser [e.g. chrome, safari] Chrome
- Version [for example, 22] 102.0.5005.115

**Smartphone (please fill in the following information):**
- Device: [for example, iPhone6] Honor 7a
- OPERATING system: [e.g. iOS8.1] Androis 10
- Browser [e.g. standard browser, safari] chrome
- Version [for example, 22] ???

**Additional context**
Add here any other context regarding this issue.
Although the notification does not appear about successful registration, the record is saved in the database, but there is no approval button in the admin panel.

**Comment by kevingorman1000** [comment] 2022-07-02 10:13
Are you able to please provide me with the exact details you used within the "new first responder" menu? I have just tried to reproduce this error and unable to do so. 

I noticed you're using the canary version of OC. Is that right? 

Also, what hosting provider/panel are you using? (CPanel, IIS etc)

Thanks

**Comment by AAndersenLves** [comment] 2022-07-02 12:02
Can you provide me with the exact information you used in the "new first responder" menu? I just tried to reproduce this error and couldn't do it.

I noticed that you are using the canary version of OC. Is that right?

Also, which hosting provider/panel do you use? (cPanel, IIS, etc.)

Thanks
I'm using the canary version. Hosting is Russian (We are a Russian community) hostiman.ru . ispmanager 5 panel 

In "first responder" I use the following data:
email: test@lves.com
name: testuser
password: qwerty123
identifier: 1111
department: CPD
If I understand you correctly, you are talking about this data. Otherwise, notify me. :)
Other data were also entered, and unsuccessfully

**Comment by kevingorman1000** [comment] 2022-07-02 12:06
Thanks for this. 

The department you added to the user, is this a department you manually added to the database or is it one from the GTAV_install.sql file? 

I'm just trying to figure out as much information as possible to try and replicate the problem. 

I'll have a look at the canary version that's on this github and see if it's a hosting issue or a OC problem. 

I'm at my sisters wedding so I'll have to have a look tonight. 

Having a quick look online, I've never personally used ISPManager 5, this may be the reason for the redirect. I'll update you tonight once I've had a play about and seen if I can reproduce this issue and find a fix for you.

**Comment by AAndersenLves** [comment] 2022-07-02 12:16
Thanks for the answer! Have a good rest! It's really cool that you devote time to the project even on your legitimate vacation.
I added the department manually to the mysql database via phpmyadmin

I apologize in advance for my broken English. I speak English poorly myself, so I use a translator and some of my personal skills (They are at the noob level) :)

**Comment by kevingorman1000** [comment] 2022-07-02 12:17
No problem. I'll try and reproduce the error when I get home tonight and let you know.

**Comment by AAndersenLves** [comment] 2022-07-02 12:18
I understand you! Good luck

**Comment by kevingorman1000** [comment] 2022-07-03 20:43
Hello, sorry for the late reply. 

I have personally been unable to replicate the issue you have been facing. 

Not sure if @ItsAGeekThing  is able to reproduce this said issue with his version? 

The version I've been working on and pushing to my [repo](https://github.com/kevingorman1000/OpenCAD-php/tree/release/canary) doesn't seem to be effected with this.

**Comment by ItsAGeekThing** [comment] 2022-07-04 03:33
> Hello, sorry for the late reply. 
> 
> I have personally been unable to replicate the issue you have been facing. 
> 
> Not sure if @ItsAGeekThing  is able to reproduce this said issue with his version? 
> 
> The version I've been working on and pushing to my [repo](https://github.com/kevingorman1000/OpenCAD-php/tree/release/canary) doesn't seem to be effected with this. 

I'll redeploy a test instance and verify.

**Comment by phillf** [comment] 2022-07-04 14:13
@AAndersenLves, I would suggest pulling a copy from Kevin's repo and seeing if you can replicate the issue still.

just a gentle reminder that canary is not meant to be used in a "production" or "live" environment.

Once you get a stable production deployment I highly recommend deploying a copy of at least beta.

**Comment by kevingorman1000** [comment] 2022-07-04 15:47
I've just been looking through the issues that are currently open, it seems like this has been reported before here: #386

@AAndersenLves The merge has been completed and worth giving it a go. I don't ever recall fixing the issue directly, but perhapes one of my other fixes resolved this issue. Please report back and let us know.

**Comment by AAndersenLves** [comment] 2022-07-05 05:03
I apologize for the long answer! As I understand it, I need to download the latest version of Opencad from Kevin's repository?
Perhaps my question sounds stupid, but I ask you to understand, since this is the first time in this topic of web development, especially php.

**Comment by kevingorman1000** [comment] 2022-07-05 05:09
My pull request has been approved, so if you redownload the canary version, ot should be exactly the same as my repo

**Comment by kevingorman1000** [comment] 2022-07-08 23:00
@AAndersenLves  Did you get a chance to test the new canary version and see if this problem has been resolved?

**Comment by AAndersenLves** [comment] 2022-07-10 10:34
Good afternoon. I apologize for the long answer - I was in the hospital. I didn't quite understand where to get the new version from. I would be grateful for a link to the exact source

**Comment by kevingorman1000** [comment] 2022-07-10 16:10
No worries. Hope all is okay. 

Here is the link you need. 

https://github.com/opencad-app/OpenCAD-php/tree/release%2Fcanary

**Comment by phillf** [comment] 2023-02-11 20:36
Seeing no further activity it is assumed that (1) the issue was resolved or (2) the user found another solutions that wasn't OC. Closing thread.

**Closed as completed by phillf** 2023-02-11 20:36 UTC
